"""Frozen authorization catalog snapshot for revision 20260825_0002.

Generated from the live registries at migration authoring time. Historical
revisions must not import auth modules that can change after merge; a later
registry edit requires a new Alembic revision instead of silently redefining
this one.
"""

FROZEN_ROLE_ROWS = [
    {
        "key": "assistant_analyst",
        "label": "Assistant Analyst",
        "description": "Assigned-scope analyst for analytics without default finance access.",
        "service_only": False,
    },
    {
        "key": "audit_viewer",
        "label": "Audit Viewer",
        "description": "Read-only audit and compliance reviewer.",
        "service_only": False,
    },
    {
        "key": "beta_operator",
        "label": "Beta Operator",
        "description": "First-beta finance operator with manual revenue-upload access.",
        "service_only": False,
    },
    {
        "key": "channel_manager",
        "label": "Channel Manager",
        "description": "Channel-scoped manager for assigned channel analytics.",
        "service_only": False,
    },
    {
        "key": "company_manager",
        "label": "Company Manager",
        "description": "Company-scoped manager for assigned company analytics.",
        "service_only": False,
    },
    {
        "key": "connector_admin",
        "label": "Connector Admin",
        "description": "Technical owner for Google/API connector credential configuration.",
        "service_only": False,
    },
    {
        "key": "corporate_admin",
        "label": "Corporate Admin",
        "description": "Global platform administrator without default finance visibility.",
        "service_only": False,
    },
    {
        "key": "data_steward",
        "label": "Data Steward",
        "description": "Scoped owner for channel registry, groups, and organization mapping.",
        "service_only": False,
    },
    {
        "key": "export_operator",
        "label": "Export Operator",
        "description": "Scoped export operator for approved analytics or finance exports.",
        "service_only": False,
    },
    {
        "key": "finance_admin",
        "label": "Finance Admin",
        "description": "Finance owner for revenue, reconciliation, overrides, and month close.",
        "service_only": False,
    },
    {
        "key": "finance_approver",
        "label": "Finance Approver",
        "description": "Second-control approver for finance overrides and month unlocks.",
        "service_only": False,
    },
    {
        "key": "finance_viewer",
        "label": "Finance Viewer",
        "description": "Read-only finance role for granted organization scopes.",
        "service_only": False,
    },
    {
        "key": "news_sector_manager",
        "label": "News Sector Manager",
        "description": "Sector-scoped management role for News analytics and report operations.",
        "service_only": False,
    },
    {
        "key": "revenue_operations_admin",
        "label": "Revenue Operations Admin",
        "description": "Global operational admin for ingestion, registry quality, and analytics.",
        "service_only": False,
    },
    {
        "key": "super_owner",
        "label": "Super Owner",
        "description": "Global break-glass owner with every platform and finance permission.",
        "service_only": False,
    },
    {
        "key": "system_integration_user",
        "label": "System Integration User",
        "description": "Non-human role for scheduled connector jobs and backend service flows.",
        "service_only": True,
    },
    {
        "key": "tv_sector_manager",
        "label": "TV Sector Manager",
        "description": "Sector-scoped management role for TV analytics and report operations.",
        "service_only": False,
    },
]

FROZEN_PERMISSION_ROWS = [
    {
        "key": "analytics.view",
        "label": "View performance analytics",
        "sensitive": False,
        "audit_on_use": False,
    },
    {
        "key": "analytics.view_confidence",
        "label": "View confidence labels and issue flags",
        "sensitive": False,
        "audit_on_use": False,
    },
    {"key": "audit.view", "label": "View audit log", "sensitive": True, "audit_on_use": True},
    {
        "key": "audit.view_sensitive_payloads",
        "label": "View sensitive audit payloads",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "connectors.manage",
        "label": "Manage connectors",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "connectors.run_jobs",
        "label": "Run connector jobs",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "connectors.view_health",
        "label": "View connector health",
        "sensitive": False,
        "audit_on_use": False,
    },
    {
        "key": "exports.analytics",
        "label": "Export analytics report",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "exports.manage_templates",
        "label": "Manage export templates",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "exports.revenue",
        "label": "Export revenue report",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.approve_manual_override",
        "label": "Approve manual override",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.change_allocation_rule",
        "label": "Change allocation rule",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.create_manual_override",
        "label": "Create manual override",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.import_manual_revenue",
        "label": "Import manual revenue facts",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.lock_month",
        "label": "Lock finance month",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.manage_bank_reconciliation",
        "label": "Manage bank reconciliation",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.unlock_month",
        "label": "Unlock finance month",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.view_bank_reconciliation",
        "label": "View bank reconciliation",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.view_finalized_payments",
        "label": "View finalized payments",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "finance.view_revenue",
        "label": "View revenue values",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "platform.manage_settings",
        "label": "Manage platform settings",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "raw_files.view",
        "label": "View raw report files",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "registry.manage_channels",
        "label": "Manage channel registry",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "registry.manage_groups",
        "label": "Manage channel groups",
        "sensitive": True,
        "audit_on_use": True,
    },
    {
        "key": "registry.manage_org_mapping",
        "label": "Manage organization mapping",
        "sensitive": True,
        "audit_on_use": True,
    },
    {"key": "roles.assign", "label": "Assign roles", "sensitive": True, "audit_on_use": True},
    {"key": "users.manage", "label": "Manage users", "sensitive": True, "audit_on_use": True},
]

FROZEN_ROLE_PERMISSION_ROWS = [
    {"role_key": "assistant_analyst", "permission_key": "analytics.view"},
    {"role_key": "assistant_analyst", "permission_key": "analytics.view_confidence"},
    {"role_key": "audit_viewer", "permission_key": "audit.view"},
    {"role_key": "beta_operator", "permission_key": "analytics.view"},
    {"role_key": "beta_operator", "permission_key": "analytics.view_confidence"},
    {"role_key": "beta_operator", "permission_key": "audit.view"},
    {"role_key": "beta_operator", "permission_key": "exports.analytics"},
    {"role_key": "beta_operator", "permission_key": "exports.revenue"},
    {"role_key": "beta_operator", "permission_key": "finance.approve_manual_override"},
    {"role_key": "beta_operator", "permission_key": "finance.change_allocation_rule"},
    {"role_key": "beta_operator", "permission_key": "finance.create_manual_override"},
    {"role_key": "beta_operator", "permission_key": "finance.import_manual_revenue"},
    {"role_key": "beta_operator", "permission_key": "finance.lock_month"},
    {"role_key": "beta_operator", "permission_key": "finance.manage_bank_reconciliation"},
    {"role_key": "beta_operator", "permission_key": "finance.unlock_month"},
    {"role_key": "beta_operator", "permission_key": "finance.view_bank_reconciliation"},
    {"role_key": "beta_operator", "permission_key": "finance.view_finalized_payments"},
    {"role_key": "beta_operator", "permission_key": "finance.view_revenue"},
    {"role_key": "channel_manager", "permission_key": "analytics.view"},
    {"role_key": "channel_manager", "permission_key": "analytics.view_confidence"},
    {"role_key": "channel_manager", "permission_key": "exports.analytics"},
    {"role_key": "company_manager", "permission_key": "analytics.view"},
    {"role_key": "company_manager", "permission_key": "analytics.view_confidence"},
    {"role_key": "company_manager", "permission_key": "exports.analytics"},
    {"role_key": "connector_admin", "permission_key": "connectors.manage"},
    {"role_key": "connector_admin", "permission_key": "connectors.run_jobs"},
    {"role_key": "connector_admin", "permission_key": "connectors.view_health"},
    {"role_key": "connector_admin", "permission_key": "raw_files.view"},
    {"role_key": "corporate_admin", "permission_key": "analytics.view"},
    {"role_key": "corporate_admin", "permission_key": "analytics.view_confidence"},
    {"role_key": "corporate_admin", "permission_key": "audit.view"},
    {"role_key": "corporate_admin", "permission_key": "connectors.view_health"},
    {"role_key": "corporate_admin", "permission_key": "exports.analytics"},
    {"role_key": "corporate_admin", "permission_key": "exports.manage_templates"},
    {"role_key": "corporate_admin", "permission_key": "platform.manage_settings"},
    {"role_key": "corporate_admin", "permission_key": "registry.manage_channels"},
    {"role_key": "corporate_admin", "permission_key": "registry.manage_groups"},
    {"role_key": "corporate_admin", "permission_key": "registry.manage_org_mapping"},
    {"role_key": "corporate_admin", "permission_key": "roles.assign"},
    {"role_key": "corporate_admin", "permission_key": "users.manage"},
    {"role_key": "data_steward", "permission_key": "analytics.view"},
    {"role_key": "data_steward", "permission_key": "analytics.view_confidence"},
    {"role_key": "data_steward", "permission_key": "registry.manage_channels"},
    {"role_key": "data_steward", "permission_key": "registry.manage_groups"},
    {"role_key": "data_steward", "permission_key": "registry.manage_org_mapping"},
    {"role_key": "export_operator", "permission_key": "analytics.view"},
    {"role_key": "export_operator", "permission_key": "analytics.view_confidence"},
    {"role_key": "export_operator", "permission_key": "exports.analytics"},
    {"role_key": "finance_admin", "permission_key": "analytics.view"},
    {"role_key": "finance_admin", "permission_key": "analytics.view_confidence"},
    {"role_key": "finance_admin", "permission_key": "audit.view"},
    {"role_key": "finance_admin", "permission_key": "exports.analytics"},
    {"role_key": "finance_admin", "permission_key": "exports.revenue"},
    {"role_key": "finance_admin", "permission_key": "finance.approve_manual_override"},
    {"role_key": "finance_admin", "permission_key": "finance.change_allocation_rule"},
    {"role_key": "finance_admin", "permission_key": "finance.create_manual_override"},
    {"role_key": "finance_admin", "permission_key": "finance.lock_month"},
    {"role_key": "finance_admin", "permission_key": "finance.manage_bank_reconciliation"},
    {"role_key": "finance_admin", "permission_key": "finance.unlock_month"},
    {"role_key": "finance_admin", "permission_key": "finance.view_bank_reconciliation"},
    {"role_key": "finance_admin", "permission_key": "finance.view_finalized_payments"},
    {"role_key": "finance_admin", "permission_key": "finance.view_revenue"},
    {"role_key": "finance_admin", "permission_key": "roles.assign"},
    {"role_key": "finance_approver", "permission_key": "analytics.view"},
    {"role_key": "finance_approver", "permission_key": "analytics.view_confidence"},
    {"role_key": "finance_approver", "permission_key": "audit.view"},
    {"role_key": "finance_approver", "permission_key": "exports.revenue"},
    {"role_key": "finance_approver", "permission_key": "finance.approve_manual_override"},
    {"role_key": "finance_approver", "permission_key": "finance.change_allocation_rule"},
    {"role_key": "finance_approver", "permission_key": "finance.manage_bank_reconciliation"},
    {"role_key": "finance_approver", "permission_key": "finance.unlock_month"},
    {"role_key": "finance_approver", "permission_key": "finance.view_bank_reconciliation"},
    {"role_key": "finance_approver", "permission_key": "finance.view_finalized_payments"},
    {"role_key": "finance_approver", "permission_key": "finance.view_revenue"},
    {"role_key": "finance_viewer", "permission_key": "analytics.view"},
    {"role_key": "finance_viewer", "permission_key": "analytics.view_confidence"},
    {"role_key": "finance_viewer", "permission_key": "finance.view_bank_reconciliation"},
    {"role_key": "finance_viewer", "permission_key": "finance.view_finalized_payments"},
    {"role_key": "finance_viewer", "permission_key": "finance.view_revenue"},
    {"role_key": "news_sector_manager", "permission_key": "analytics.view"},
    {"role_key": "news_sector_manager", "permission_key": "analytics.view_confidence"},
    {"role_key": "news_sector_manager", "permission_key": "exports.analytics"},
    {"role_key": "revenue_operations_admin", "permission_key": "analytics.view"},
    {"role_key": "revenue_operations_admin", "permission_key": "analytics.view_confidence"},
    {"role_key": "revenue_operations_admin", "permission_key": "connectors.run_jobs"},
    {"role_key": "revenue_operations_admin", "permission_key": "connectors.view_health"},
    {"role_key": "revenue_operations_admin", "permission_key": "exports.analytics"},
    {"role_key": "revenue_operations_admin", "permission_key": "registry.manage_channels"},
    {"role_key": "revenue_operations_admin", "permission_key": "registry.manage_groups"},
    {"role_key": "revenue_operations_admin", "permission_key": "registry.manage_org_mapping"},
    {"role_key": "super_owner", "permission_key": "analytics.view"},
    {"role_key": "super_owner", "permission_key": "analytics.view_confidence"},
    {"role_key": "super_owner", "permission_key": "audit.view"},
    {"role_key": "super_owner", "permission_key": "audit.view_sensitive_payloads"},
    {"role_key": "super_owner", "permission_key": "connectors.manage"},
    {"role_key": "super_owner", "permission_key": "connectors.run_jobs"},
    {"role_key": "super_owner", "permission_key": "connectors.view_health"},
    {"role_key": "super_owner", "permission_key": "exports.analytics"},
    {"role_key": "super_owner", "permission_key": "exports.manage_templates"},
    {"role_key": "super_owner", "permission_key": "exports.revenue"},
    {"role_key": "super_owner", "permission_key": "finance.approve_manual_override"},
    {"role_key": "super_owner", "permission_key": "finance.change_allocation_rule"},
    {"role_key": "super_owner", "permission_key": "finance.create_manual_override"},
    {"role_key": "super_owner", "permission_key": "finance.import_manual_revenue"},
    {"role_key": "super_owner", "permission_key": "finance.lock_month"},
    {"role_key": "super_owner", "permission_key": "finance.manage_bank_reconciliation"},
    {"role_key": "super_owner", "permission_key": "finance.unlock_month"},
    {"role_key": "super_owner", "permission_key": "finance.view_bank_reconciliation"},
    {"role_key": "super_owner", "permission_key": "finance.view_finalized_payments"},
    {"role_key": "super_owner", "permission_key": "finance.view_revenue"},
    {"role_key": "super_owner", "permission_key": "platform.manage_settings"},
    {"role_key": "super_owner", "permission_key": "raw_files.view"},
    {"role_key": "super_owner", "permission_key": "registry.manage_channels"},
    {"role_key": "super_owner", "permission_key": "registry.manage_groups"},
    {"role_key": "super_owner", "permission_key": "registry.manage_org_mapping"},
    {"role_key": "super_owner", "permission_key": "roles.assign"},
    {"role_key": "super_owner", "permission_key": "users.manage"},
    {"role_key": "system_integration_user", "permission_key": "connectors.run_jobs"},
    {"role_key": "system_integration_user", "permission_key": "connectors.view_health"},
    {"role_key": "tv_sector_manager", "permission_key": "analytics.view"},
    {"role_key": "tv_sector_manager", "permission_key": "analytics.view_confidence"},
    {"role_key": "tv_sector_manager", "permission_key": "exports.analytics"},
]
