"""Immutable snapshot of the ISO 4217 currency list as of 2026-05.

DO NOT MUTATE. Future updates land as a new dated module (e.g.
iso_4217_2027_03.py) referenced by a new migration. Each entry is a
plain dict so historical migrations cannot break if downstream
dataclasses (connectors/google_source_rows/dataclasses.py) ever change.
"""

from typing import Final

ISO_4217_CURRENCIES_2026_05: Final[tuple[dict[str, object], ...]] = (
    {"code": "AED", "numeric_code": "784", "name": "UAE Dirham", "minor_unit": 2},
    {"code": "AFN", "numeric_code": "971", "name": "Afghani", "minor_unit": 2},
    {"code": "ALL", "numeric_code": "008", "name": "Lek", "minor_unit": 2},
    {"code": "AMD", "numeric_code": "051", "name": "Armenian Dram", "minor_unit": 2},
    {"code": "ANG", "numeric_code": "532", "name": "Netherlands Antillean Guilder", "minor_unit": 2},
    {"code": "AOA", "numeric_code": "973", "name": "Kwanza", "minor_unit": 2},
    {"code": "ARS", "numeric_code": "032", "name": "Argentine Peso", "minor_unit": 2},
    {"code": "AUD", "numeric_code": "036", "name": "Australian Dollar", "minor_unit": 2},
    {"code": "AWG", "numeric_code": "533", "name": "Aruban Florin", "minor_unit": 2},
    {"code": "AZN", "numeric_code": "944", "name": "Azerbaijan Manat", "minor_unit": 2},
    {"code": "BAM", "numeric_code": "977", "name": "Convertible Mark", "minor_unit": 2},
    {"code": "BBD", "numeric_code": "052", "name": "Barbados Dollar", "minor_unit": 2},
    {"code": "BDT", "numeric_code": "050", "name": "Taka", "minor_unit": 2},
    {"code": "BGN", "numeric_code": "975", "name": "Bulgarian Lev", "minor_unit": 2},
    {"code": "BHD", "numeric_code": "048", "name": "Bahraini Dinar", "minor_unit": 3},
    {"code": "BIF", "numeric_code": "108", "name": "Burundi Franc", "minor_unit": 0},
    {"code": "BMD", "numeric_code": "060", "name": "Bermudian Dollar", "minor_unit": 2},
    {"code": "BND", "numeric_code": "096", "name": "Brunei Dollar", "minor_unit": 2},
    {"code": "BOB", "numeric_code": "068", "name": "Boliviano", "minor_unit": 2},
    {"code": "BOV", "numeric_code": "984", "name": "Mvdol", "minor_unit": 2},
    {"code": "BRL", "numeric_code": "986", "name": "Brazilian Real", "minor_unit": 2},
    {"code": "BSD", "numeric_code": "044", "name": "Bahamian Dollar", "minor_unit": 2},
    {"code": "BTN", "numeric_code": "064", "name": "Ngultrum", "minor_unit": 2},
    {"code": "BWP", "numeric_code": "072", "name": "Pula", "minor_unit": 2},
    {"code": "BYN", "numeric_code": "933", "name": "Belarusian Ruble", "minor_unit": 2},
    {"code": "BZD", "numeric_code": "084", "name": "Belize Dollar", "minor_unit": 2},
    {"code": "CAD", "numeric_code": "124", "name": "Canadian Dollar", "minor_unit": 2},
    {"code": "CDF", "numeric_code": "976", "name": "Congolese Franc", "minor_unit": 2},
    {"code": "CHE", "numeric_code": "947", "name": "WIR Euro", "minor_unit": 2},
    {"code": "CHF", "numeric_code": "756", "name": "Swiss Franc", "minor_unit": 2},
    {"code": "CHW", "numeric_code": "948", "name": "WIR Franc", "minor_unit": 2},
    {"code": "CLF", "numeric_code": "990", "name": "Unidad de Fomento", "minor_unit": 4},
    {"code": "CLP", "numeric_code": "152", "name": "Chilean Peso", "minor_unit": 0},
    {"code": "CNY", "numeric_code": "156", "name": "Yuan Renminbi", "minor_unit": 2},
    {"code": "COP", "numeric_code": "170", "name": "Colombian Peso", "minor_unit": 2},
    {"code": "COU", "numeric_code": "970", "name": "Unidad de Valor Real", "minor_unit": 2},
    {"code": "CRC", "numeric_code": "188", "name": "Costa Rican Colon", "minor_unit": 2},
    {"code": "CUP", "numeric_code": "192", "name": "Cuban Peso", "minor_unit": 2},
    {"code": "CVE", "numeric_code": "132", "name": "Cabo Verde Escudo", "minor_unit": 2},
    {"code": "CZK", "numeric_code": "203", "name": "Czech Koruna", "minor_unit": 2},
    {"code": "DJF", "numeric_code": "262", "name": "Djibouti Franc", "minor_unit": 0},
    {"code": "DKK", "numeric_code": "208", "name": "Danish Krone", "minor_unit": 2},
    {"code": "DOP", "numeric_code": "214", "name": "Dominican Peso", "minor_unit": 2},
    {"code": "DZD", "numeric_code": "012", "name": "Algerian Dinar", "minor_unit": 2},
    {"code": "EGP", "numeric_code": "818", "name": "Egyptian Pound", "minor_unit": 2},
    {"code": "ERN", "numeric_code": "232", "name": "Nakfa", "minor_unit": 2},
    {"code": "ETB", "numeric_code": "230", "name": "Ethiopian Birr", "minor_unit": 2},
    {"code": "EUR", "numeric_code": "978", "name": "Euro", "minor_unit": 2},
    {"code": "FJD", "numeric_code": "242", "name": "Fiji Dollar", "minor_unit": 2},
    {"code": "FKP", "numeric_code": "238", "name": "Falkland Islands Pound", "minor_unit": 2},
    {"code": "GBP", "numeric_code": "826", "name": "Pound Sterling", "minor_unit": 2},
    {"code": "GEL", "numeric_code": "981", "name": "Lari", "minor_unit": 2},
    {"code": "GHS", "numeric_code": "936", "name": "Ghana Cedi", "minor_unit": 2},
    {"code": "GIP", "numeric_code": "292", "name": "Gibraltar Pound", "minor_unit": 2},
    {"code": "GMD", "numeric_code": "270", "name": "Dalasi", "minor_unit": 2},
    {"code": "GNF", "numeric_code": "324", "name": "Guinean Franc", "minor_unit": 0},
    {"code": "GTQ", "numeric_code": "320", "name": "Quetzal", "minor_unit": 2},
    {"code": "GYD", "numeric_code": "328", "name": "Guyana Dollar", "minor_unit": 2},
    {"code": "HKD", "numeric_code": "344", "name": "Hong Kong Dollar", "minor_unit": 2},
    {"code": "HNL", "numeric_code": "340", "name": "Lempira", "minor_unit": 2},
    {"code": "HTG", "numeric_code": "332", "name": "Gourde", "minor_unit": 2},
    {"code": "HUF", "numeric_code": "348", "name": "Forint", "minor_unit": 2},
    {"code": "IDR", "numeric_code": "360", "name": "Rupiah", "minor_unit": 2},
    {"code": "ILS", "numeric_code": "376", "name": "New Israeli Sheqel", "minor_unit": 2},
    {"code": "INR", "numeric_code": "356", "name": "Indian Rupee", "minor_unit": 2},
    {"code": "IQD", "numeric_code": "368", "name": "Iraqi Dinar", "minor_unit": 3},
    {"code": "IRR", "numeric_code": "364", "name": "Iranian Rial", "minor_unit": 2},
    {"code": "ISK", "numeric_code": "352", "name": "Iceland Krona", "minor_unit": 0},
    {"code": "JMD", "numeric_code": "388", "name": "Jamaican Dollar", "minor_unit": 2},
    {"code": "JOD", "numeric_code": "400", "name": "Jordanian Dinar", "minor_unit": 3},
    {"code": "JPY", "numeric_code": "392", "name": "Yen", "minor_unit": 0},
    {"code": "KES", "numeric_code": "404", "name": "Kenyan Shilling", "minor_unit": 2},
    {"code": "KGS", "numeric_code": "417", "name": "Som", "minor_unit": 2},
    {"code": "KHR", "numeric_code": "116", "name": "Riel", "minor_unit": 2},
    {"code": "KMF", "numeric_code": "174", "name": "Comorian Franc", "minor_unit": 0},
    {"code": "KPW", "numeric_code": "408", "name": "North Korean Won", "minor_unit": 2},
    {"code": "KRW", "numeric_code": "410", "name": "Won", "minor_unit": 0},
    {"code": "KWD", "numeric_code": "414", "name": "Kuwaiti Dinar", "minor_unit": 3},
    {"code": "KYD", "numeric_code": "136", "name": "Cayman Islands Dollar", "minor_unit": 2},
    {"code": "KZT", "numeric_code": "398", "name": "Tenge", "minor_unit": 2},
    {"code": "LAK", "numeric_code": "418", "name": "Lao Kip", "minor_unit": 2},
    {"code": "LBP", "numeric_code": "422", "name": "Lebanese Pound", "minor_unit": 2},
    {"code": "LKR", "numeric_code": "144", "name": "Sri Lanka Rupee", "minor_unit": 2},
    {"code": "LRD", "numeric_code": "430", "name": "Liberian Dollar", "minor_unit": 2},
    {"code": "LSL", "numeric_code": "426", "name": "Loti", "minor_unit": 2},
    {"code": "LYD", "numeric_code": "434", "name": "Libyan Dinar", "minor_unit": 3},
    {"code": "MAD", "numeric_code": "504", "name": "Moroccan Dirham", "minor_unit": 2},
    {"code": "MDL", "numeric_code": "498", "name": "Moldovan Leu", "minor_unit": 2},
    {"code": "MGA", "numeric_code": "969", "name": "Malagasy Ariary", "minor_unit": 2},
    {"code": "MKD", "numeric_code": "807", "name": "Denar", "minor_unit": 2},
    {"code": "MMK", "numeric_code": "104", "name": "Kyat", "minor_unit": 2},
    {"code": "MNT", "numeric_code": "496", "name": "Tugrik", "minor_unit": 2},
    {"code": "MOP", "numeric_code": "446", "name": "Pataca", "minor_unit": 2},
    {"code": "MRU", "numeric_code": "929", "name": "Ouguiya", "minor_unit": 2},
    {"code": "MUR", "numeric_code": "480", "name": "Mauritius Rupee", "minor_unit": 2},
    {"code": "MVR", "numeric_code": "462", "name": "Rufiyaa", "minor_unit": 2},
    {"code": "MWK", "numeric_code": "454", "name": "Malawi Kwacha", "minor_unit": 2},
    {"code": "MXN", "numeric_code": "484", "name": "Mexican Peso", "minor_unit": 2},
    {"code": "MXV", "numeric_code": "979", "name": "Mexican Unidad de Inversion (UDI)", "minor_unit": 2},
    {"code": "MYR", "numeric_code": "458", "name": "Malaysian Ringgit", "minor_unit": 2},
    {"code": "MZN", "numeric_code": "943", "name": "Mozambique Metical", "minor_unit": 2},
    {"code": "NAD", "numeric_code": "516", "name": "Namibia Dollar", "minor_unit": 2},
    {"code": "NGN", "numeric_code": "566", "name": "Naira", "minor_unit": 2},
    {"code": "NIO", "numeric_code": "558", "name": "Cordoba Oro", "minor_unit": 2},
    {"code": "NOK", "numeric_code": "578", "name": "Norwegian Krone", "minor_unit": 2},
    {"code": "NPR", "numeric_code": "524", "name": "Nepalese Rupee", "minor_unit": 2},
    {"code": "NZD", "numeric_code": "554", "name": "New Zealand Dollar", "minor_unit": 2},
    {"code": "OMR", "numeric_code": "512", "name": "Rial Omani", "minor_unit": 3},
    {"code": "PAB", "numeric_code": "590", "name": "Balboa", "minor_unit": 2},
    {"code": "PEN", "numeric_code": "604", "name": "Sol", "minor_unit": 2},
    {"code": "PGK", "numeric_code": "598", "name": "Kina", "minor_unit": 2},
    {"code": "PHP", "numeric_code": "608", "name": "Philippine Peso", "minor_unit": 2},
    {"code": "PKR", "numeric_code": "586", "name": "Pakistan Rupee", "minor_unit": 2},
    {"code": "PLN", "numeric_code": "985", "name": "Zloty", "minor_unit": 2},
    {"code": "PYG", "numeric_code": "600", "name": "Guarani", "minor_unit": 0},
    {"code": "QAR", "numeric_code": "634", "name": "Qatari Rial", "minor_unit": 2},
    {"code": "RON", "numeric_code": "946", "name": "Romanian Leu", "minor_unit": 2},
    {"code": "RSD", "numeric_code": "941", "name": "Serbian Dinar", "minor_unit": 2},
    {"code": "RUB", "numeric_code": "643", "name": "Russian Ruble", "minor_unit": 2},
    {"code": "RWF", "numeric_code": "646", "name": "Rwanda Franc", "minor_unit": 0},
    {"code": "SAR", "numeric_code": "682", "name": "Saudi Riyal", "minor_unit": 2},
    {"code": "SBD", "numeric_code": "090", "name": "Solomon Islands Dollar", "minor_unit": 2},
    {"code": "SCR", "numeric_code": "690", "name": "Seychelles Rupee", "minor_unit": 2},
    {"code": "SDG", "numeric_code": "938", "name": "Sudanese Pound", "minor_unit": 2},
    {"code": "SEK", "numeric_code": "752", "name": "Swedish Krona", "minor_unit": 2},
    {"code": "SGD", "numeric_code": "702", "name": "Singapore Dollar", "minor_unit": 2},
    {"code": "SHP", "numeric_code": "654", "name": "Saint Helena Pound", "minor_unit": 2},
    {"code": "SLE", "numeric_code": "925", "name": "Leone", "minor_unit": 2},
    {"code": "SOS", "numeric_code": "706", "name": "Somali Shilling", "minor_unit": 2},
    {"code": "SRD", "numeric_code": "968", "name": "Surinam Dollar", "minor_unit": 2},
    {"code": "SSP", "numeric_code": "728", "name": "South Sudanese Pound", "minor_unit": 2},
    {"code": "STN", "numeric_code": "930", "name": "Dobra", "minor_unit": 2},
    {"code": "SVC", "numeric_code": "222", "name": "El Salvador Colon", "minor_unit": 2},
    {"code": "SYP", "numeric_code": "760", "name": "Syrian Pound", "minor_unit": 2},
    {"code": "SZL", "numeric_code": "748", "name": "Lilangeni", "minor_unit": 2},
    {"code": "THB", "numeric_code": "764", "name": "Baht", "minor_unit": 2},
    {"code": "TJS", "numeric_code": "972", "name": "Somoni", "minor_unit": 2},
    {"code": "TMT", "numeric_code": "934", "name": "Turkmenistan New Manat", "minor_unit": 2},
    {"code": "TND", "numeric_code": "788", "name": "Tunisian Dinar", "minor_unit": 3},
    {"code": "TOP", "numeric_code": "776", "name": "Pa'anga", "minor_unit": 2},
    {"code": "TRY", "numeric_code": "949", "name": "Turkish Lira", "minor_unit": 2},
    {"code": "TTD", "numeric_code": "780", "name": "Trinidad and Tobago Dollar", "minor_unit": 2},
    {"code": "TWD", "numeric_code": "901", "name": "New Taiwan Dollar", "minor_unit": 2},
    {"code": "TZS", "numeric_code": "834", "name": "Tanzanian Shilling", "minor_unit": 2},
    {"code": "UAH", "numeric_code": "980", "name": "Hryvnia", "minor_unit": 2},
    {"code": "UGX", "numeric_code": "800", "name": "Uganda Shilling", "minor_unit": 0},
    {"code": "USD", "numeric_code": "840", "name": "US Dollar", "minor_unit": 2},
    {"code": "USN", "numeric_code": "997", "name": "US Dollar (Next day)", "minor_unit": 2},
    {"code": "UYI", "numeric_code": "940", "name": "Uruguay Peso en Unidades Indexadas (UI)", "minor_unit": 0},
    {"code": "UYU", "numeric_code": "858", "name": "Peso Uruguayo", "minor_unit": 2},
    {"code": "UZS", "numeric_code": "860", "name": "Uzbekistan Sum", "minor_unit": 2},
    {"code": "VED", "numeric_code": "926", "name": "Bolivar Soberano", "minor_unit": 2},
    {"code": "VES", "numeric_code": "928", "name": "Bolivar Soberano", "minor_unit": 2},
    {"code": "VND", "numeric_code": "704", "name": "Dong", "minor_unit": 0},
    {"code": "VUV", "numeric_code": "548", "name": "Vatu", "minor_unit": 0},
    {"code": "WST", "numeric_code": "882", "name": "Tala", "minor_unit": 2},
    {"code": "XAF", "numeric_code": "950", "name": "CFA Franc BEAC", "minor_unit": 0},
    {"code": "XAG", "numeric_code": "961", "name": "Silver", "minor_unit": None},
    {"code": "XAU", "numeric_code": "959", "name": "Gold", "minor_unit": None},
    {
        "code": "XBA",
        "numeric_code": "955",
        "name": "Bond Markets Unit European Composite Unit (EURCO)",
        "minor_unit": None,
    },
    {
        "code": "XBB",
        "numeric_code": "956",
        "name": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
        "minor_unit": None,
    },
    {
        "code": "XBC",
        "numeric_code": "957",
        "name": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
        "minor_unit": None,
    },
    {
        "code": "XBD",
        "numeric_code": "958",
        "name": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
        "minor_unit": None,
    },
    {"code": "XCD", "numeric_code": "951", "name": "East Caribbean Dollar", "minor_unit": 2},
    {"code": "XDR", "numeric_code": "960", "name": "SDR (Special Drawing Right)", "minor_unit": None},
    {"code": "XOF", "numeric_code": "952", "name": "CFA Franc BCEAO", "minor_unit": 0},
    {"code": "XPD", "numeric_code": "964", "name": "Palladium", "minor_unit": None},
    {"code": "XPF", "numeric_code": "953", "name": "CFP Franc", "minor_unit": 0},
    {"code": "XPT", "numeric_code": "962", "name": "Platinum", "minor_unit": None},
    {"code": "XSU", "numeric_code": "994", "name": "Sucre", "minor_unit": None},
    {
        "code": "XTS",
        "numeric_code": "963",
        "name": "Codes specifically reserved for testing purposes",
        "minor_unit": None,
    },
    {"code": "XUA", "numeric_code": "965", "name": "ADB Unit of Account", "minor_unit": None},
    {
        "code": "XXX",
        "numeric_code": "999",
        "name": "The codes assigned for transactions where no currency is involved",
        "minor_unit": None,
    },
    {"code": "YER", "numeric_code": "886", "name": "Yemeni Rial", "minor_unit": 2},
    {"code": "ZAR", "numeric_code": "710", "name": "Rand", "minor_unit": 2},
    {"code": "ZMW", "numeric_code": "967", "name": "Zambian Kwacha", "minor_unit": 2},
    {"code": "ZWG", "numeric_code": "924", "name": "Zimbabwe Gold", "minor_unit": 2},
)
